

module sns{


sequence<string> StringList_t;
sequence<int>	IntList_t;

sequence<string> UserIdList_t;
sequence<string> SIDS_t;
dictionary<string,string> StrStr_t;
sequence<StrStr_t> StrStrList_t;
sequence<byte> 	StreamByte_t;

dictionary<int,StreamByte_t> StreamMap_t;
sequence<StreamByte_t>  StreamArray_t;

//interface and data modals definations

struct GeoPoint_t{
	float lon;
	float lat;
};

struct GeoSize_t{
	float cx;
	float cy;
};

struct GeoCircle_t{
	GeoPoint_t center;
	float radius;
};

struct GeoRect_t{
	float x;
	float y;
	float width;
	float height;
};

struct GpsInfo_t{
	GeoPoint_t loc;
	float speed;
	float direction;
	int   timesec; 
};

struct LocationInfo_t{
	string		user_id;
	GpsInfo_t 	gps;
	string 		desc;
};
sequence<LocationInfo_t> LocationInfoList_t;


struct ImageThumbInfo_t{
	StreamByte_t content;
};

interface IBaseServer{
	int getServerTimestamp();
	void test1(StreamByte_t s,string s2);
	int test2(StreamByte_t s);
	StreamByte_t test3(int aa);

//	StreamList_t getImageList();
//	void putImageList(StreamArray_t images);
};


}

//-- stranger -----------------------------

