

module test{

[index=1,enable=true,name="scott"]
interface BaseServer{
	[index=10]
	string datetime();
};


interface ITerminalGatewayServer{
	void ping();
};


interface Server extends BaseServer{
	string echo(string text);
	void  timeout(int secs);
	void heartbeat(string hello);
	void bidirection();
};


interface ITerminal{
    void onMessage(string  message);
};

}

//-- stranger -----------------------------

