

module test{

[index=11,comment="base server"]
interface BaseServer{
	[index=10]
	string datetime();
};


interface ITerminalGatewayServer{
	void ping();
};

[skeleton_js=false,skeleton_objc=false,skeleton_as=false,skeleton_cpp=false,skeleton_csharp=false,skeleton_java=true,comment=""]
interface Server extends BaseServer{
	string echo(string text);
	void  timeout(int secs);
	void heartbeat(string hello);
	void bidirection();
};


interface ITerminal{
    void onMessage(string  message);
};

}

//-- stranger -----------------------------

