

//#import <Foundation/Foundation.h>

#define RPC_PACKET_HDR_SIZE 17
#define COMPRESS_NONE   0
#define COMPRESS_ZLIB   1
#define COMPRESS_BZIP2  2

#define ENCRYPT_NONE    0
#define ENCRYPT_MD5     1
#define ENCRYPT_DES     2

#define MSGTYPE_RPC     1
#define MSGTYPE_NORPC   2

#define CONNECTION_UNKNOWN 0
#define CONNECTION_SOCK 1
#define CONNECTION_HTTP 2

#define MSG_ENCODE_BIN  0x10
#define MSG_ENCODE_XML  0x20

#define ASYNC_RPCMSG    0x01


enum RpcErrorCodeType_t{
    RPCERROR_SUCC = 0,
    RPCERROR_SENDFAILED =1,
    RPCERROR_DATADIRTY= 3,
    RPCERROR_TIMEOUT = 2,
    RPCERROR_INTERFACE_NOTFOUND = 4,
    RPCERROR_UNSERIALIZE_FAILED = 5,
    RPCERROR_REMOTEMETHOD_EXCEPTION = 6,
    RPCERROR_DATA_INSUFFICIENT = 7,
    RPCERROR_REMOTE_EXCEPTION = 8,
    RPCERROR_CONNECT_UNREACHABLE = 101,
    RPCERROR_CONNECT_FAILED  = 102,
    RPCERROR_CONNECT_REJECT = 103,
    RPCERROR_CONNECTION_LOST = 104,
    RPCERROR_INTERNAL_EXCEPTION = 105,
	RPCERROR_TOKEN_INVALID = 106, //用户token 过期失效

};

//typedef void (^async_call_block)(void);




